name: flutter_app # 应用或包名称
description: A new Flutter application. # 应用或包的描述、简介

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1 # 应用或包的版本号
author: 师春雷 <1558053958@qq.com>
homepage: https://github.com/shichunlei/flutter_app

publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies: # 应用或包依赖的其它包或插件
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 地图定位
  amap_location_fluttify: ^0.17.0

  # https://github.com/aagarwal1012/Animated-Text-Kit
  animated_text_kit: ^4.2.1

  # 音频播放
  audioplayers: ^0.19.0

  # AzListView，Flutter 城市列表，联系人列表，自定义Header，索引，悬停效果。
  azlistview: ^2.0.0-nullsafety.0

  badges: ^1.1.6

  # 条形码
  barcode_flutter: ^1.1.2

  # 扫描二维码
  barcode_scan: ^2.0.2

  # 带缓存的图片
  cached_network_image: ^3.0.0

  chewie: ^1.2.2

  convert: ^3.0.0

  clippy_flutter: ^2.0.0-nullsafety.1

  # 设备信息
  device_info: ^2.0.2

  # 网络请求库
  dio: ^4.0.0

  easy_contact_picker: ^0.0.2

  # 英文单词库
  english_words: ^4.0.0

  encrypt: any

  fancy_bottom_navigation: ^0.3.3

  # flare 插件
  flare_flutter: ^2.0.6

  flutter_charts:
    git:
      url: https://github.com/shichunlei/flutter_charts

  # 颜色选择器
  flutter_colorpicker: ^0.5.0

  # 刷新加载控件
  flutter_easyrefresh: ^2.2.1

  # 侧滑菜单
  flutter_inner_drawer: 0.5.7+1

  # 仿京东地址选择器
  flutter_jd_address_selector:
    git:
      url: https://github.com/shichunlei/flutter_jd_address_selector

  flutter_libs:
    path: flutter_libs/

  # https://github.com/dooboolab/flutter_sound
#  flutter_sound: ^2.1.1

  # 加载提示组件
  flutter_spinkit: ^5.0.0

  # 瀑布流
  flutter_staggered_grid_view: ^0.4.0

  # banner
  flutter_swiper: ^1.1.6

  # 集成图标库
  # FontAwesome 地址：http://www.fontawesome.com.cn/
  # Feather 地址：https://feathericons.com/
  # EvilIcons 地址：https://evil-icons.io/
  # AntDesign 地址：https://ant.design/components/icon/
  # Ionicons 地址：https://ionicons.com
  # Fontisto 地址：https://fontisto.com/icons
  # Foundation 地址：https://zurb.com/playground/foundation-icon-fonts-3
  # Octicons 地址：https://octicons.github.com/
  # SimpleLineIcons 地址：https://simplelineicons.github.io/
  flutter_vector_icons: ^1.0.0

  # 天气背景
  flutter_weather_bg_null_safety: ^1.0.0

  # webview
  flutter_webview_plugin: ^0.4.0

  flutter_widget_from_html: ^0.6.1

  # 图片裁剪
  image_cropper: ^1.4.0

  # 图片保存
  image_gallery_saver: ^1.6.9

  # 图片选择器
  image_picker: ^0.8.0+3

  # 汉字转拼音库 https://github.com/flutterchina/lpinyin
  lpinyin: ^2.0.3

  modal_bottom_sheet: ^2.0.0

  multi_image_picker: ^4.8.0

  package_info: ^2.0.2

  palette_generator: ^0.3.0

  # 滑动视差效果图片 https://github.com/pulyaevskiy/parallax-image
  parallax_image: ^0.3.1+1

#  path_provider: ^2.0.0

  # 权限管理
  permission_handler: ^7.2.0

  # PhotoView
  photo_view: ^0.11.1

  # 数据管理层
  provider: ^5.0.0

  # flutter 生成二维码
  qr_flutter: ^3.2.0

  quiver: ^2.0.0

  #
  rounded_letter: ^0.0.6

  share: ^2.0.1

  # SP
  shared_preferences: ^2.0.5

  # 对 flare API进行封装的插件，使用少量的代码即可实现交互动画
  smart_flare: ^0.2.9+1

  # 数据库
  # sqflite: ^1.3.1+1

  # 时间线 https://github.com/furkantektas/timeline_list
  timeline_list: ^0.0.5

  # 透明占位图片
  transparent_image: ^2.0.0

  url_launcher: ^6.0.6

  # 手机震动
  vibration: ^1.7.4-nullsafety.0

  wave: ^0.2.0

dev_dependencies: # 开发环境依赖的工具包（而不是flutter应用本身依赖的包）
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter. flutter相关的配置选项
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class. https://material.io/tools/icons/?icon=sd_storage&style=baseline
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/weather_backgrounds/
    - images/qdaily/
    - images/reader/
    - images/tag_icons/
    - images/flare/
    - assets/data/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/custom/iconfont.ttf

    - family: Aleo
      fonts:
        - asset: assets/fonts/Aleo-Regular.ttf
        - asset: assets/fonts/Aleo-Italic.ttf
          style: italic
        - asset: assets/fonts/Aleo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Aleo-Light.ttf
          weight: 300

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true